name: Ruff

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Add uv to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync --dev

    - name: Run ruff check
      run: uv run ruff check .

    - name: Run ruff format check
      run: uv run ruff format --check .